services:
  vite-react22222:
    ports:
      - 3000:3000
      - 5173:5173
      - 4000:4000
    stdin_open: true
    tty: true
    build: .
    volumes:
      - .:/app
    command:
      sh -c "yarn install && yarn cmp dev"
